sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install -e .[test]
  - pip install coveralls
script:
  - CXX=g++-5 py.test tests
after_success:
  - coveralls
